name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./sitoweb/frontend

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.pages-url.outputs.url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Pages
        uses: actions/deploy-pages@v1
